# Generated by Django 3.1.4 on 2020-12-22 10:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoUSA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='New Jersey', max_length=250)),
                ('county', models.CharField(choices=[('Atlantic County', 'Atlantic County'), ('Bergen County', 'Bergen County'), ('Burlington County', 'Burlington County'), ('Camden County', 'Camden County'), ('Cape May County', 'Cape May County'), ('Cumberland County', 'Cumberland County'), ('Essex County', 'Essex County'), ('Gloucestor County', 'Gloucestor County'), ('Hudson County', 'Hudson County'), ('Hunterdon County', 'Hunterdon County'), ('Mercer County', 'Mercer County'), ('Middlesex County', 'Middlesex County'), ('Monmouth County', 'Monmouth County'), ('Morris County', 'Morris County'), ('Ocean County', 'Ocean County'), ('Passaic County', 'Passaic County'), ('Salem County', 'Salem County'), ('Somerset County', 'Somerset County'), ('Sussex County', 'Sussex County'), ('Union County', 'Union County'), ('Warren County', 'Warren County')], max_length=250)),
                ('name', models.CharField(max_length=2500)),
                ('poly', django.contrib.gis.db.models.fields.PolygonField(srid=4269)),
            ],
        ),
    ]
