# Generated by Django 3.1.4 on 2020-12-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geousa',
            name='name',
            field=models.CharField(max_length=2500),
        ),
    ]
