# Generated by Django 3.1.4 on 2021-03-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geousa',
            name='zone_info',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
    ]
