# Generated by Django 3.1.4 on 2021-03-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0002_geousa_zone_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='geousa',
            name='fld_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
