# Generated by Django 3.1.4 on 2021-08-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0003_geousa_fld_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geousa',
            name='county',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
