# Generated by Django 3.1.4 on 2021-01-27 13:25

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usda', '0002_auto_20210127_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geousda',
            name='poly',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4269),
        ),
    ]
