# Generated by Django 3.1.4 on 2021-01-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usda', '0003_auto_20210127_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geousda',
            name='state',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
