# Generated by Django 3.1.4 on 2021-01-29 13:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoOppurtunityZones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=250)),
                ('county', models.CharField(max_length=250)),
                ('poly', django.contrib.gis.db.models.fields.PolygonField(srid=4269)),
            ],
        ),
    ]
