# Generated by Django 3.1.4 on 2021-01-29 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oppurtunity', '0002_auto_20210129_1305'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeoOppurtunityZones',
            new_name='GeoOppurtunityZone',
        ),
    ]
