# Generated by Django 3.1.4 on 2021-02-01 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oppurtunity', '0003_auto_20210129_1305'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeoOppurtunityZone',
            new_name='GeoOpportunityZone',
        ),
    ]
